require 'digest/md5'
require 'io/console'
class Encryptor

  def initialize
    last_rotation = 0
    @last_rotation = last_rotation
  end

  def run
    puts "Welcome to Encryptor"
    authenticate_user
    command = ""
    while command != "quit"
      puts ""
      printf "enter command: "
      input = gets.chomp
      parts = input.split
      command = parts[0]
      case command
        when "quit"
          puts "Goodbye! Encryptor is shutting down."
        when "e"
          @last_rotation = rand(91)
          puts encrypt(parts[1..-1].join(" "), @last_rotation)
        when "er"
          puts encrypt(parts[2..-1].join(" "), parts[1].to_i)
        when "d"
          puts decrypt(parts[1..-1].join(" "), @last_rotation)
        when "dr"
          puts decrypt(parts[2..-1].join(" "), parts[1].to_i)
        when "help"
          puts "
          // quit - exits the program
          // e (message) - encrypts a message using a randomly generated encryption rotation.
          // er (message, rotation) - encrypts a message using the specified rotation number.
          // d (message) - decrypts a message using the last rotation number generated by the 'e' command.
          // dr (message, rotation) - decrypts a message using the specified rotation number."
        else
          puts "Unknown command, please try again."
      end
    end
  end

  def authenticate_user
    puts "Please enter the secret password: "
    pwd_try = STDIN.noecho(&:gets)
    pwd_try_encrypted = encrypt(pwd_try, 12)
    pkey = "%t&zpq#om%$"
    pkey_md5 = Digest::MD5.hexdigest(pkey)
    pwd_try_md5 = Digest::MD5.hexdigest(pwd_try_encrypted)
    if pwd_try_md5 != pkey_md5
      puts "You have entered an incorrect password. Aborting."
      fail
    end
  end

  def cipher(rotation)
    characters = (' '..'z').to_a
    rotated_characters = characters.rotate(rotation)
    Hash[characters.zip(rotated_characters)]
  end

  def encrypt_letter (letter, rotation)
    cipher_for_rotation = cipher(rotation)
    cipher_for_rotation[letter]
  end

  def encrypt(string, rotation)
    letters = string.split("")
    results = letters.collect do |letter|
      encrypt_letter(letter, rotation)
    end
    results.join
  end

  def decrypt_letter (letter, rotation)
    cipher_for_rotation = cipher(-rotation)
    cipher_for_rotation[letter]
  end

  def decrypt(string, rotation = last_rotation)
    letters = string.split("")
    results = letters.collect do |letter|
      decrypt_letter(letter, rotation)
    end
    results.join
  end

  def encrypt_file(filename, rotation)
    file_in = File.open(filename, "r")
    encrypted_mojo = encrypt(file_in.read, rotation)
    file_out = File.open("encrypted_#{filename}", "w")
    file_out.write(encrypted_mojo)
    file_out.close
  end

  def decrypt_file(filename, rotation)
    file_in = File.open(filename, "r")
    decrypted_mojo = decrypt(file_in.read, rotation)
    file_out = File.open("decrypted_#{filename}", "w")
    file_out.write(decrypted_mojo)
    file_out.close
  end

  def supported_characters
    (' '..'z').to_a
  end

  def crack(message)
    supported_characters.count.times.collect do |attempt|
      decrypt(message,attempt)
    end
  end

end

encryptor = Encryptor.new
encryptor.run